### ISSUE TITLE
验证或者测试或者demo测试时候出错：tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by Kennycao123** [LowinLi/Text-Summarizer-Pytorch-Chinese#12]
data/chunked/valid/valid_*
2021-01-09 19:33:08,215 - data_util.log - INFO - 
Traceback (most recent call last):
  File "eval.py", line 170, in <module>
    eval_processor.evaluate_batch(False)
  File "eval.py", line 78, in evaluate_batch
    start_id, end_id, unk_id)
  File "/media//DATA/code/nlp/summary/Text-Summarizer-Pytorch-Chinese-master/beam_search.py", line 179, in beam_search
    sum_temporal_srcs_i, prev_s_i)
  File "/media/DATA/code/nlp/summary/Text-Summarizer-Pytorch-Chinese-master/beam_search.py", line 54, in advance
    self.hid_h = h[beams_order]  #(beam, n_hid); sorted
IndexError: tensors used as indices must be long, byte or bool tensors

训练过程没问题。测试或者验证时候总会出现beam_search代码中索引不对的问题，，想问下是什么原因。

**Comment by LowinLi** [comment]
这里期待long、byte、bool的tensors格式，您可以debug一下，看看这里输入了什么样的格式数据

**Comment by skywalk163** [comment]
我也碰到这个问题了，输入的数据beams_order是：tensor([0.0037, 0.0435, 0.0029, 0.0251], device='cuda:0')
将库版本切换回官方设定的版本，就不报错了
```
torch==1.5.0
tensorflow==2.2.0
jieba==0.42.1
tqdm==4.46.0
pandas==1.0.3
rouge
```
