### ISSUE TITLE
运行python /tmp/bishe/eval.py --task=validate --start_from=0005000.tar命令时遇到除零错误

### ISSUE THREAD

**Issue by starryscholar** [LowinLi/Text-Summarizer-Pytorch-Chinese#23]
(myconda) root@cebf7236c869:~# python /tmp/bishe/eval.py --task=validate --start_from=0005000.tar
2021-05-13 01:43:28,991 - data_util.log - INFO - log鍚姩
/tmp/bishe/data/chunked/valid/valid_*
2021-05-13 01:43:31,420 - data_util.log - INFO - 
Traceback (most recent call last):
  File "/tmp/bishe/eval.py", line 168, in <module>
    eval_processor.evaluate_batch(False)
  File "/tmp/bishe/eval.py", line 102, in evaluate_batch
    rouge_1 = sum([x["rouge-1"]["f"] for x in scores]) / len(scores)
ZeroDivisionError: division by zero
![image](https://user-images.githubusercontent.com/49752990/118020839-27894400-b38d-11eb-8bc9-923e07639c11.png)
代码：
        if article:
            self.print_original_predicted(decoded_sents, ref_sents,
                                          article_sents, load_file)

        scores = rouge.get_scores(decoded_sents, ref_sents)
        rouge_1 = sum([x["rouge-1"]["f"] for x in scores]) / len(scores)
        rouge_2 = sum([x["rouge-2"]["f"] for x in scores]) / len(scores)
        rouge_l = sum([x["rouge-l"]["f"] for x in scores]) / len(scores)
        logger.info(load_file + " rouge_1:" + "%.4f" % rouge_1 + " rouge_2:" + "%.4f" % rouge_2 + " rouge_l:" + "%.4f" % rouge_l)
![image](https://user-images.githubusercontent.com/49752990/118021096-720ac080-b38d-11eb-9832-de3998b9d602.png)

**Comment by LowinLi** [comment]
会不会是传入了空的验证集呢

**Comment by starryscholar** [comment]
> 会不会是传入了空的验证集呢

![image](https://user-images.githubusercontent.com/49752990/118293920-c25c5c80-b50c-11eb-9afb-09773d56971c.png)
![image](https://user-images.githubusercontent.com/49752990/118293963-cd16f180-b50c-11eb-8192-e39bf4c1fb0c.png)
是这个验证集吗，有的呀
