### ISSUE TITLE
请问一下运行eval时报的错，怎末处理

### ISSUE THREAD

**Issue by mlm22222** [LowinLi/Text-Summarizer-Pytorch-Chinese#35]
Traceback (most recent call last):
  File "D:/Text-Summarizer-Pytorch-Chinese-master/eval.py", line 171, in <module>
    eval_processor.evaluate_batch(True)
  File "D:/Text-Summarizer-Pytorch-Chinese-master/eval.py", line 78, in evaluate_batch
    start_id, end_id, unk_id)
  File "D:\Text-Summarizer-Pytorch-Chinese-master\beam_search.py", line 179, in beam_search
    sum_temporal_srcs_i, prev_s_i).type(T.long)
  File "D:\Text-Summarizer-Pytorch-Chinese-master\beam_search.py", line 54, in advance
    self.hid_h = h[beams_order]  #(beam, n_hid); sorted
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by LowinLi** [comment]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by LowinLi** [comment]
```
IndexError: tensors used as indices must be long, byte or bool tensors
```

建议debug下

**Comment by suancaimian** [comment]
查了下说是用float当索引错误，我改成了long类型，改成bool类型后面cat会报错

**Comment by suancaimian** [comment]
是用的win么？我也遇到了，应该是索引的问题，但是在linux就没报错

**Comment by JJJJerry** [comment]
把 
beams_order = best_scores_id.squeeze(1) / n_extended_vocab
改成
beams_order = best_scores_id.squeeze(1) // n_extended_vocab
